# Generated by Django 5.0.4 on 2024-05-29 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0011_remove_profile_answer_remove_profile_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="answer_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="comment_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="question_id",
        ),
    ]
