# Generated by Django 5.0.4 on 2024-05-30 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0012_remove_profile_answer_id_remove_profile_comment_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="self_introduction",
        ),
        migrations.AddField(
            model_name="profile",
            name="introduction",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
